name: Build and Deploy

on:
   push:
      branches:
         - main

jobs:
   build-and-deploy:
      runs-on: ubuntu-latest
      steps:
         - name: Checkout 🛎️
           uses: actions/checkout@v2.3.1
           with:
              persist-credentials: false
         - name: Install and Build 🔧
           run: | # Install npm packages and build the Storybook files
              cd packages/react
              npm install
              npm run build-storybook
         - name: Deploy 🚀
           uses: JamesIves/github-pages-deploy-action@3.6.2
           with:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              BRANCH: gh-pages # The branch the action should deploy to.
              FOLDER: storybook-static # The folder that the build-storybook script generates files.
